spring:
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/shops
     username: root
     password: MySQL@123
  jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true

server:
  port: 8086